### ISSUE TITLE
Slice bounds out of range in App.generateHandler…→UTF8Reader.Read

### ISSUE THREAD

**Issue by nilium** [yudai/gotty#3]
Saw a crash when a second client connected to gotty into a tmux session holding `htop` (i.e., ran via `gotty tmux attach -t gotty` to show it to a coworker, 'cause this is pretty awesome).

```
$ tmux new-session -s gotty htop
…
$ gotty tmux attach -t gotty
2015/08/17 07:59:02 Sever is running at :8080, command: tmux attach -t gotty
2015/08/17 07:59:04 New client connected: 10.0.3.89:58751
2015/08/17 07:59:26 New client connected: 10.0.3.211:63808
panic: runtime error: slice bounds out of range

goroutine 5 [running]:
github.com/yudai/utf8reader.(*UTF8Reader).Read(0xc82003ef58, 0xc82021c800, 0x400, 0x400, 0x400, 0x0, 0x0)
	GOPATH/src/github.com/yudai/utf8reader/utf8reader.go:47 +0x2ca
github.com/yudai/gotty/app.(*App).generateHandler.func1.1(0xc8201e1e30, 0xc820032018, 0xc820112460, 0xc8201101e0)
	GOPATH/src/github.com/yudai/gotty/app/app.go:89 +0x1f3
created by github.com/yudai/gotty/app.(*App).generateHandler.func1
	GOPATH/src/github.com/yudai/gotty/app/app.go:103 +0x5d3

… other goroutines behaving normally …
```

Unfortunately haven't been able to reproduce it, so possibly a fluke. Figured I'd open an issue and if I come up on other details I'll amend the issue.

**Comment by yudai** [comment]
Thank you for the report.
It was a kind of corner case and I overlooked it.
A new release with the fix is now available on the releases page.
Thank you!

**Comment by nilium** [comment]
Awesome!
