### ISSUE TITLE
nil pointer dereference

### ISSUE THREAD

**Issue by nongiach** [yudai/gotty#89]
2016/02/14 02:24:14 Server is starting with command: tmux new -A -s gotty top
2016/02/14 02:24:14 URL: http://127.0.0.1:8080/
2016/02/14 02:24:14 URL: http://[::1]:8080/
2016/02/14 02:24:14 URL: http://my_ip:8080/
2016/02/14 02:24:14 URL: http://my_ip:8080/
2016/02/14 02:24:14 URL: http://[fe80::601:a8ff:fed5:5a01]:8080/
2016/02/14 02:24:20 http: panic serving my_ip:11108: runtime error: invalid memory address or nil pointer dereference
goroutine 11 [running]:
net/http.(*conn).serve.func1(0xc8200922c0, 0x7fb638edbc30, 0xc820028058)
	/usr/lib/go/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc820013380, 0xc82000fc40, 0x11, 0x0, 0x0, 0x0, 0x0)
	/home/kog/.go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0x7fb638edbde8, 0xc82000faa0, 0xc8200960e0, 0x7fb638eda930, 0xc820013380, 0x80d6c0, 0x1, 0xc800000001)
	/usr/lib/go/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc820094250, 0x7fb638edbde8, 0xc82000faa0, 0xc8200960e0)
	/usr/lib/go/src/net/http/fs.go:483 +0x19c
net/http.StripPrefix.func1(0x7fb638edbde8, 0xc82000faa0, 0xc8200960e0)
	/usr/lib/go/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc820013410, 0x7fb638edbde8, 0xc82000faa0, 0xc8200960e0)
	/usr/lib/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc8200133e0, 0x7fb638edbde8, 0xc82000faa0, 0xc8200960e0)
	/usr/lib/go/src/net/http/server.go:1699 +0x17d
github.com/yudai/gotty/app.wrapHeaders.func1(0x7fb638edbde8, 0xc82000faa0, 0xc8200960e0)
	/home/kog/.go/src/github.com/yudai/gotty/app/app.go:389 +0xf1
net/http.HandlerFunc.ServeHTTP(0xc82000f0a0, 0x7fb638edbde8, 0xc82000faa0, 0xc8200960e0)
	/usr/lib/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc8200134d0, 0x7fb638edbde8, 0xc82000faa0, 0xc8200960e0)
	/usr/lib/go/src/net/http/server.go:1699 +0x17d
github.com/yudai/gotty/app.wrapLogger.func1(0x7fb638edbdb0, 0xc820092420, 0xc8200960e0)
	/home/kog/.go/src/github.com/yudai/gotty/app/app.go:381 +0xd0
net/http.HandlerFunc.ServeHTTP(0xc82000f0e0, 0x7fb638edbdb0, 0xc820092420, 0xc8200960e0)
	/usr/lib/go/src/net/http/server.go:1422 +0x3a
github.com/braintree/manners.(*gracefulHandler).ServeHTTP(0xc82000f920, 0x7fb638edbdb0, 0xc820092420, 0xc8200960e0)
	/home/kog/.go/src/github.com/braintree/manners/server.go:262 +0x7e
net/http.serverHandler.ServeHTTP(0xc82001a4e0, 0x7fb638edbdb0, 0xc820092420, 0xc8200960e0)
	/usr/lib/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200922c0)
	/usr/lib/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1910 +0x3f6

**Comment by nongiach** [comment]
sorry this has been already reported
