### ISSUE TITLE
http: panic serving 192.168.1.8:36501: runtime error: invalid memory address or nil pointer dereference goroutine 18 [running]:

### ISSUE THREAD

**Issue by rounin** [yudai/gotty#90]
Hello,
I start with default setting but somehow the stack trace shows a different port number:

```
-=#=-
rounin@rounin:~/go_dir/program$ go get github.com/yudai/gotty
rounin@rounin:~/go_dir/program$ which gotty
/home/rounin/go_dir/go1.5.3/bin/gotty
rounin@rounin:~/go_dir/program$ gotty top
2016/02/20 18:32:29 Server is starting with command: top
2016/02/20 18:32:29 URL: http://127.0.0.1:8080/
2016/02/20 18:32:29 URL: http://[::1]:8080/
2016/02/20 18:32:29 URL: http://192.168.1.8:8080/
2016/02/20 18:32:29 URL: http://[removed]:8080/
2016/02/20 18:32:37 http: panic serving 192.168.1.8:36501: runtime error: invalid memory address or nil pointer dereference
goroutine 18 [running]:
net/http.(*conn).serve.func1(0xc8200da000, 0x7f0d9dfdd000, 0xc8200d8000)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200134a0, 0xc8200de260, 0x11, 0x0, 0x0, 0x0, 0x0)
	/home/rounin/go_dir/gopath/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0x7f0d9dfdd1b8, 0xc8200de0a0, 0xc8200ea000, 0x7f0da0025930, 0xc8200134a0, 0x80e730, 0x1, 0xc800000001)
	/home/rounin/go_dir/go1.5.3/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200aa2d0, 0x7f0d9dfdd1b8, 0xc8200de0a0, 0xc8200ea000)
	/home/rounin/go_dir/go1.5.3/src/net/http/fs.go:483 +0x19c
net/http.StripPrefix.func1(0x7f0d9dfdd1b8, 0xc8200de0a0, 0xc8200ea000)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc820013530, 0x7f0d9dfdd1b8, 0xc8200de0a0, 0xc8200ea000)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820013500, 0x7f0d9dfdd1b8, 0xc8200de0a0, 0xc8200ea000)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1699 +0x17d
github.com/yudai/gotty/app.wrapHeaders.func1(0x7f0d9dfdd1b8, 0xc8200de0a0, 0xc8200ea000)
	/home/rounin/go_dir/gopath/src/github.com/yudai/gotty/app/app.go:389 +0xf1
net/http.HandlerFunc.ServeHTTP(0xc82000b360, 0x7f0d9dfdd1b8, 0xc8200de0a0, 0xc8200ea000)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc8200135f0, 0x7f0d9dfdd1b8, 0xc8200de0a0, 0xc8200ea000)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1699 +0x17d
github.com/yudai/gotty/app.wrapLogger.func1(0x7f0d9dfdd180, 0xc8200da0b0, 0xc8200ea000)
	/home/rounin/go_dir/gopath/src/github.com/yudai/gotty/app/app.go:381 +0xd0
net/http.HandlerFunc.ServeHTTP(0xc82000b3a0, 0x7f0d9dfdd180, 0xc8200da0b0, 0xc8200ea000)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1422 +0x3a
github.com/braintree/manners.(*gracefulHandler).ServeHTTP(0xc82000bac0, 0x7f0d9dfdd180, 0xc8200da0b0, 0xc8200ea000)
	/home/rounin/go_dir/gopath/src/github.com/braintree/manners/server.go:262 +0x7e
net/http.serverHandler.ServeHTTP(0xc82001a4e0, 0x7f0d9dfdd180, 0xc8200da0b0, 0xc8200ea000)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200da000)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1910 +0x3f6

^C2016/02/20 18:33:14 Received Exit command, waiting for all clients to close sessions...
Send ^C to force exit.
2016/02/20 18:33:14 Exiting...
rounin@rounin:~/go_dir/program$ uname -a
Linux rounin 3.16.0-53-generic #72~14.04.1-Ubuntu SMP Fri Nov 6 18:17:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
rounin@rounin:~/go_dir/program$ date
Sat Feb 20 18:33:24 GMT 2016
rounin@rounin:~/go_dir/program$ 
rounin@rounin:~/go_dir/program$ gotty top
2016/02/20 18:34:24 Server is starting with command: top
2016/02/20 18:34:24 URL: http://127.0.0.1:8080/
2016/02/20 18:34:24 URL: http://[::1]:8080/
2016/02/20 18:34:24 URL: http://[removed]:8080/
2016/02/20 18:34:40 http: panic serving 127.0.0.1:38447: runtime error: invalid memory address or nil pointer dereference
goroutine 25 [running]:
net/http.(*conn).serve.func1(0xc8200ea000, 0x7f28f0252b20, 0xc820092048)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200772f0, 0xc8200fc1e0, 0x11, 0x0, 0x0, 0x0, 0x0)
	/home/rounin/go_dir/gopath/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0x7f28f020d090, 0xc8200fc020, 0xc8200c6460, 0x7f28f0251908, 0xc8200772f0, 0x80e730, 0x1, 0xc800000001)
	/home/rounin/go_dir/go1.5.3/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200c4150, 0x7f28f020d090, 0xc8200fc020, 0xc8200c6460)
	/home/rounin/go_dir/go1.5.3/src/net/http/fs.go:483 +0x19c
net/http.StripPrefix.func1(0x7f28f020d090, 0xc8200fc020, 0xc8200c6460)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc820077380, 0x7f28f020d090, 0xc8200fc020, 0xc8200c6460)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820077350, 0x7f28f020d090, 0xc8200fc020, 0xc8200c6460)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1699 +0x17d
github.com/yudai/gotty/app.wrapHeaders.func1(0x7f28f020d090, 0xc8200fc020, 0xc8200c6460)
	/home/rounin/go_dir/gopath/src/github.com/yudai/gotty/app/app.go:389 +0xf1
net/http.HandlerFunc.ServeHTTP(0xc820094fc0, 0x7f28f020d090, 0xc8200fc020, 0xc8200c6460)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820077440, 0x7f28f020d090, 0xc8200fc020, 0xc8200c6460)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1699 +0x17d
github.com/yudai/gotty/app.wrapLogger.func1(0x7f28f020d058, 0xc8200fe000, 0xc8200c6460)
	/home/rounin/go_dir/gopath/src/github.com/yudai/gotty/app/app.go:381 +0xd0
net/http.HandlerFunc.ServeHTTP(0xc820095000, 0x7f28f020d058, 0xc8200fe000, 0xc8200c6460)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1422 +0x3a
github.com/braintree/manners.(*gracefulHandler).ServeHTTP(0xc820095640, 0x7f28f020d058, 0xc8200fe000, 0xc8200c6460)
	/home/rounin/go_dir/gopath/src/github.com/braintree/manners/server.go:262 +0x7e
net/http.serverHandler.ServeHTTP(0xc8200723c0, 0x7f28f020d058, 0xc8200fe000, 0xc8200c6460)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200ea000)
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/home/rounin/go_dir/go1.5.3/src/net/http/server.go:1910 +0x3f6
^C2016/02/20 18:35:09 Received Exit command, waiting for all clients to close sessions...
Send ^C to force exit.
2016/02/20 18:35:09 Exiting...

-=#=-
```
Thanks,
ROuNIN

**Comment by i223t** [comment]
Same issue

**Comment by norwat** [comment]
+1

**Comment by corpix** [comment]
Have just installed this so popular tool and it is not working:
```
$ gotty -p 8536 vi
2016/04/04 11:35:00 Server is starting with command: vi
2016/04/04 11:35:00 URL: http://127.0.0.1:8536/
2016/04/04 11:35:00 URL: http://[::1]:8536/
2016/04/04 11:35:00 URL: http://172.16.0.3:8536/
2016/04/04 11:35:00 URL: http://[fe80::5054:ff:fe12:c575]:8536/
2016/04/04 11:35:02 http: panic serving 127.0.0.1:46878: runtime error: invalid memory address or nil pointer dereference
goroutine 23 [running]:
net/http.(*conn).serve.func1(0xc8200f0000, 0x7fcf05b82978, 0xc820084048)
	/usr/lib/golang/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc820014120, 0xc82000eb80, 0x11, 0x0, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0x7fcf079c32d0, 0xc82000e9e0, 0xc8200c00e0, 0x7fcf079c2028, 0xc820014120, 0x80a210, 0x1, 0xc800000001)
	/usr/lib/golang/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200101a0, 0x7fcf079c32d0, 0xc82000e9e0, 0xc8200c00e0)
	/usr/lib/golang/src/net/http/fs.go:483 +0x19c
net/http.StripPrefix.func1(0x7fcf079c32d0, 0xc82000e9e0, 0xc8200c00e0)
	/usr/lib/golang/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200141b0, 0x7fcf079c32d0, 0xc82000e9e0, 0xc8200c00e0)
	/usr/lib/golang/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820014180, 0x7fcf079c32d0, 0xc82000e9e0, 0xc8200c00e0)
	/usr/lib/golang/src/net/http/server.go:1699 +0x17d
github.com/yudai/gotty/app.wrapHeaders.func1(0x7fcf079c32d0, 0xc82000e9e0, 0xc8200c00e0)
	/home/user/go/src/github.com/yudai/gotty/app/app.go:389 +0xf1
net/http.HandlerFunc.ServeHTTP(0xc82000e360, 0x7fcf079c32d0, 0xc82000e9e0, 0xc8200c00e0)
	/usr/lib/golang/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820014270, 0x7fcf079c32d0, 0xc82000e9e0, 0xc8200c00e0)
	/usr/lib/golang/src/net/http/server.go:1699 +0x17d
github.com/yudai/gotty/app.wrapLogger.func1(0x7fcf079c3298, 0xc8200ea160, 0xc8200c00e0)
	/home/user/go/src/github.com/yudai/gotty/app/app.go:381 +0xd0
net/http.HandlerFunc.ServeHTTP(0xc82000e3a0, 0x7fcf079c3298, 0xc8200ea160, 0xc8200c00e0)
	/usr/lib/golang/src/net/http/server.go:1422 +0x3a
github.com/braintree/manners.(*gracefulHandler).ServeHTTP(0xc82000e980, 0x7fcf079c3298, 0xc8200ea160, 0xc8200c00e0)
	/home/user/go/src/github.com/braintree/manners/server.go:277 +0x7e
net/http.serverHandler.ServeHTTP(0xc82001a120, 0x7fcf079c3298, 0xc8200ea160, 0xc8200c00e0)
	/usr/lib/golang/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200f0000)
	/usr/lib/golang/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:1910 +0x3f6
```

**Comment by yudai** [comment]
Thank you for the reports. I'll take look into the issue and get back soon.

**Comment by yudai** [comment]
Closing as this is the same error as one repoted in #90 . Please follow #90 for further update.
