### ISSUE TITLE
problem on kali 2.0

### ISSUE THREAD

**Issue by mehranexpert** [yudai/gotty#96]
```
gocode/bin/gotty -a 10.211.55.12 -w top
2016/04/12 21:19:53 Permitting clients to write input to the PTY.
2016/04/12 21:19:53 Server is starting with command: top
2016/04/12 21:19:53 URL: http://10.211.55.12:8080/
2016/04/12 21:19:58 http: panic serving 10.211.55.2:52617: runtime error: invalid memory address or nil pointer dereference
goroutine 24 [running]:
net/http.func·011()
	/usr/lib/go/src/pkg/net/http/server.go:1100 +0xb1
runtime.panic(0x82d55e0, 0x84d3353)
	/usr/lib/go/src/pkg/runtime/panic.c:248 +0x176
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0x18722b40, 0x187235a0, 0x11, 0x0, 0x0, 0x0, 0x0)
	/root/gocode/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x191
net/http.serveFile(0xb74d3870, 0x18740690, 0x18728150, 0xb74d2670, 0x18722b40, 0x82f81c0, 0x1, 0x1)
	/usr/lib/go/src/pkg/net/http/fs.go:382 +0x383
net/http.(*fileHandler).ServeHTTP(0x187003b0, 0xb74d3870, 0x18740690, 0x18728150)
	/usr/lib/go/src/pkg/net/http/fs.go:445 +0x14a
net/http.func·012(0xb74d3870, 0x18740690, 0x18728150)
	/usr/lib/go/src/pkg/net/http/server.go:1267 +0xab
net/http.HandlerFunc.ServeHTTP(0x18740530, 0xb74d3870, 0x18740690, 0x18728150)
	/usr/lib/go/src/pkg/net/http/server.go:1235 +0x41
net/http.(*ServeMux).ServeHTTP(0x18723020, 0xb74d3870, 0x18740690, 0x18728150)
	/usr/lib/go/src/pkg/net/http/server.go:1511 +0x12c
github.com/yudai/gotty/app.func·002(0xb74d3870, 0x18740690, 0x18728150)
	/root/gocode/src/github.com/yudai/gotty/app/app.go:389 +0xbd
net/http.HandlerFunc.ServeHTTP(0x18700408, 0xb74d3870, 0x18740690, 0x18728150)
	/usr/lib/go/src/pkg/net/http/server.go:1235 +0x41
net/http.(*ServeMux).ServeHTTP(0x18723060, 0xb74d3870, 0x18740690, 0x18728150)
	/usr/lib/go/src/pkg/net/http/server.go:1511 +0x12c
github.com/yudai/gotty/app.func·001(0xb74d3850, 0x187281c0, 0x18728150)
	/root/gocode/src/github.com/yudai/gotty/app/app.go:381 +0x9d
net/http.HandlerFunc.ServeHTTP(0x18700418, 0xb74d3850, 0x187281c0, 0x18728150)
	/usr/lib/go/src/pkg/net/http/server.go:1235 +0x41
github.com/braintree/manners.(*gracefulHandler).ServeHTTP(0x187405c0, 0xb74d3850, 0x187281c0, 0x18728150)
	/root/gocode/src/github.com/braintree/manners/server.go:277 +0x74
net/http.serverHandler.ServeHTTP(0x187302c0, 0xb74d3850, 0x187281c0, 0x18728150)
	/usr/lib/go/src/pkg/net/http/server.go:1673 +0x155
net/http.(*conn).serve(0x1872c280)
	/usr/lib/go/src/pkg/net/http/server.go:1174 +0x8c6
created by net/http.(*Server).Serve
	/usr/lib/go/src/pkg/net/http/server.go:1721 +0x2be
2016/04/12 21:19:58 http: panic serving 10.211.55.2:52618: runtime error: invalid memory address or nil pointer dereference
goroutine 25 [running]:
net/http.func·011()
	/usr/lib/go/src/pkg/net/http/server.go:1100 +0xb1
runtime.panic(0x82d55e0, 0x84d3353)
	/usr/lib/go/src/pkg/runtime/panic.c:248 +0x176
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0x18722b40, 0x187238e0, 0x11, 0x0, 0x0, 0x0, 0x0)
	/root/gocode/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x191
net/http.serveFile(0xb74d3870, 0x187407d0, 0x18728310, 0xb74d2670, 0x18722b40, 0x82f81c0, 0x1, 0x1)
	/usr/lib/go/src/pkg/net/http/fs.go:382 +0x383
net/http.(*fileHandler).ServeHTTP(0x187003b0, 0xb74d3870, 0x187407d0, 0x18728310)
	/usr/lib/go/src/pkg/net/http/fs.go:445 +0x14a
net/http.func·012(0xb74d3870, 0x187407d0, 0x18728310)
	/usr/lib/go/src/pkg/net/http/server.go:1267 +0xab
net/http.HandlerFunc.ServeHTTP(0x18740530, 0xb74d3870, 0x187407d0, 0x18728310)
	/usr/lib/go/src/pkg/net/http/server.go:1235 +0x41
net/http.(*ServeMux).ServeHTTP(0x18723020, 0xb74d3870, 0x187407d0, 0x18728310)
	/usr/lib/go/src/pkg/net/http/server.go:1511 +0x12c
github.com/yudai/gotty/app.func·002(0xb74d3870, 0x187407d0, 0x18728310)
	/root/gocode/src/github.com/yudai/gotty/app/app.go:389 +0xbd
net/http.HandlerFunc.ServeHTTP(0x18700408, 0xb74d3870, 0x187407d0, 0x18728310)
	/usr/lib/go/src/pkg/net/http/server.go:1235 +0x41
net/http.(*ServeMux).ServeHTTP(0x18723060, 0xb74d3870, 0x187407d0, 0x18728310)
	/usr/lib/go/src/pkg/net/http/server.go:1511 +0x12c
github.com/yudai/gotty/app.func·001(0xb74d3850, 0x18728380, 0x18728310)
	/root/gocode/src/github.com/yudai/gotty/app/app.go:381 +0x9d
net/http.HandlerFunc.ServeHTTP(0x18700418, 0xb74d3850, 0x18728380, 0x18728310)
	/usr/lib/go/src/pkg/net/http/server.go:1235 +0x41
github.com/braintree/manners.(*gracefulHandler).ServeHTTP(0x187405c0, 0xb74d3850, 0x18728380, 0x18728310)
	/root/gocode/src/github.com/braintree/manners/server.go:277 +0x74
net/http.serverHandler.ServeHTTP(0x187302c0, 0xb74d3850, 0x18728380, 0x18728310)
	/usr/lib/go/src/pkg/net/http/server.go:1673 +0x155
net/http.(*conn).serve(0x1872c370)
	/usr/lib/go/src/pkg/net/http/server.go:1174 +0x8c6
created by net/http.(*Server).Serve
	/usr/lib/go/src/pkg/net/http/server.go:1721 +0x2be
2016/04/12 21:19:58 http: panic serving 10.211.55.2:52620: runtime error: invalid memory address or nil pointer dereference
goroutine 26 [running]:
net/http.func·011()
	/usr/lib/go/src/pkg/net/http/server.go:1100 +0xb1
runtime.panic(0x82d55e0, 0x84d3353)
	/usr/lib/go/src/pkg/runtime/panic.c:248 +0x176
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0x18722b40, 0x187234e0, 0x11, 0x0, 0x0, 0x0, 0x0)
	/root/gocode/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x191
net/http.serveFile(0xb74d3870, 0x18740510, 0x18728000, 0xb74d2670, 0x18722b40, 0x82f81c0, 0x1, 0x1)
	/usr/lib/go/src/pkg/net/http/fs.go:382 +0x383
net/http.(*fileHandler).ServeHTTP(0x187003b0, 0xb74d3870, 0x18740510, 0x18728000)
	/usr/lib/go/src/pkg/net/http/fs.go:445 +0x14a
net/http.func·012(0xb74d3870, 0x18740510, 0x18728000)
	/usr/lib/go/src/pkg/net/http/server.go:1267 +0xab
net/http.HandlerFunc.ServeHTTP(0x18740530, 0xb74d3870, 0x18740510, 0x18728000)
	/usr/lib/go/src/pkg/net/http/server.go:1235 +0x41
net/http.(*ServeMux).ServeHTTP(0x18723020, 0xb74d3870, 0x18740510, 0x18728000)
	/usr/lib/go/src/pkg/net/http/server.go:1511 +0x12c
github.com/yudai/gotty/app.func·002(0xb74d3870, 0x18740510, 0x18728000)
	/root/gocode/src/github.com/yudai/gotty/app/app.go:389 +0xbd
net/http.HandlerFunc.ServeHTTP(0x18700408, 0xb74d3870, 0x18740510, 0x18728000)
	/usr/lib/go/src/pkg/net/http/server.go:1235 +0x41
net/http.(*ServeMux).ServeHTTP(0x18723060, 0xb74d3870, 0x18740510, 0x18728000)
	/usr/lib/go/src/pkg/net/http/server.go:1511 +0x12c
github.com/yudai/gotty/app.func·001(0xb74d3850, 0x18728150, 0x18728000)
	/root/gocode/src/github.com/yudai/gotty/app/app.go:381 +0x9d
net/http.HandlerFunc.ServeHTTP(0x18700418, 0xb74d3850, 0x18728150, 0x18728000)
	/usr/lib/go/src/pkg/net/http/server.go:1235 +0x41
github.com/braintree/manners.(*gracefulHandler).ServeHTTP(0x187405c0, 0xb74d3850, 0x18728150, 0x18728000)
	/root/gocode/src/github.com/braintree/manners/server.go:277 +0x74
net/http.serverHandler.ServeHTTP(0x187302c0, 0xb74d3850, 0x18728150, 0x18728000)
	/usr/lib/go/src/pkg/net/http/server.go:1673 +0x155
net/http.(*conn).serve(0x1872c1e0)
	/usr/lib/go/src/pkg/net/http/server.go:1174 +0x8c6
created by net/http.(*Server).Serve
	/usr/lib/go/src/pkg/net/http/server.go:1721 +0x2be
2016/04/12 21:20:17 http: panic serving 10.211.55.12:44577: runtime error: invalid memory address or nil pointer dereference
goroutine 27 [running]:
net/http.func·011()
	/usr/lib/go/src/pkg/net/http/server.go:1100 +0xb1
runtime.panic(0x82d55e0, 0x84d3353)
	/usr/lib/go/src/pkg/runtime/panic.c:248 +0x176
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0x18722b40, 0x18723980, 0x11, 0x0, 0x0, 0x0, 0x0)
	/root/gocode/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x191
net/http.serveFile(0xb74d3870, 0x18740750, 0x187281c0, 0xb74d2670, 0x18722b40, 0x82f81c0, 0x1, 0x1)
	/usr/lib/go/src/pkg/net/http/fs.go:382 +0x383
net/http.(*fileHandler).ServeHTTP(0x187003b0, 0xb74d3870, 0x18740750, 0x187281c0)
	/usr/lib/go/src/pkg/net/http/fs.go:445 +0x14a
net/http.func·012(0xb74d3870, 0x18740750, 0x187281c0)
	/usr/lib/go/src/pkg/net/http/server.go:1267 +0xab
net/http.HandlerFunc.ServeHTTP(0x18740530, 0xb74d3870, 0x18740750, 0x187281c0)
	/usr/lib/go/src/pkg/net/http/server.go:1235 +0x41
net/http.(*ServeMux).ServeHTTP(0x18723020, 0xb74d3870, 0x18740750, 0x187281c0)
	/usr/lib/go/src/pkg/net/http/server.go:1511 +0x12c
github.com/yudai/gotty/app.func·002(0xb74d3870, 0x18740750, 0x187281c0)
	/root/gocode/src/github.com/yudai/gotty/app/app.go:389 +0xbd
net/http.HandlerFunc.ServeHTTP(0x18700408, 0xb74d3870, 0x18740750, 0x187281c0)
	/usr/lib/go/src/pkg/net/http/server.go:1235 +0x41
net/http.(*ServeMux).ServeHTTP(0x18723060, 0xb74d3870, 0x18740750, 0x187281c0)
	/usr/lib/go/src/pkg/net/http/server.go:1511 +0x12c
github.com/yudai/gotty/app.func·001(0xb74d3850, 0x187282a0, 0x187281c0)
	/root/gocode/src/github.com/yudai/gotty/app/app.go:381 +0x9d
net/http.HandlerFunc.ServeHTTP(0x18700418, 0xb74d3850, 0x187282a0, 0x187281c0)
	/usr/lib/go/src/pkg/net/http/server.go:1235 +0x41
github.com/braintree/manners.(*gracefulHandler).ServeHTTP(0x187405c0, 0xb74d3850, 0x187282a0, 0x187281c0)
	/root/gocode/src/github.com/braintree/manners/server.go:277 +0x74
net/http.serverHandler.ServeHTTP(0x187302c0, 0xb74d3850, 0x187282a0, 0x187281c0)
	/usr/lib/go/src/pkg/net/http/server.go:1673 +0x155
net/http.(*conn).serve(0x1872c2d0)
	/usr/lib/go/src/pkg/net/http/server.go:1174 +0x8c6
created by net/http.(*Server).Serve
	/usr/lib/go/src/pkg/net/http/server.go:1721 +0x2be


```

**Comment by yudai** [comment]
Hi @mehranexpert, Thanks for the feed back.
How did you install the binary? If you used `go get`, could you try the one posted in the release page?

**Comment by yudai** [comment]
This is a duplication of #83. Please follow the #83 for further information
