### ISSUE TITLE
docker build from source, and run across below issue.

### ISSUE THREAD

**Issue by xiaods** [yudai/gotty#98]
i use https://github.com/dit4c/dockerfile-gotty to build a gotty docker image, when i run the container, i came across below error:
```
2016/04/15 16:24:47 http: panic serving 192.168.99.1:53982: runtime error: invalid memory address or nil pointer dereference
goroutine 9 [running]:
net/http.func·011()
        /usr/lib/go/src/net/http/server.go:1130 +0xbb
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc20800d1a0, 0xc20802e760, 0x11, 0x0, 0x0, 0x0, 0x0)
        /tmp/gotty/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x232
net/http.serveFile(0x7ff015fe4680, 0xc20802e4e0, 0xc208034750, 0x7ff015fe32a8, 0xc20800d1a0, 0x7a40d0, 0x1, 0x7a4001)
        /usr/lib/go/src/net/http/fs.go:389 +0x478
net/http.(*fileHandler).ServeHTTP(0xc20802bc90, 0x7ff015fe4680, 0xc20802e4e0, 0xc208034750)
        /usr/lib/go/src/net/http/fs.go:452 +0x1b1
net/http.func·012(0x7ff015fe4680, 0xc20802e4e0, 0xc208034750)
        /usr/lib/go/src/net/http/server.go:1297 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc20802eac0, 0x7ff015fe4680, 0xc20802e4e0, 0xc208034750)
        /usr/lib/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20800d200, 0x7ff015fe4680, 0xc20802e4e0, 0xc208034750)
        /usr/lib/go/src/net/http/server.go:1541 +0x17d
github.com/yudai/gotty/app.func·002(0x7ff015fe4680, 0xc20802e4e0, 0xc208034750)
        /tmp/gotty/src/github.com/yudai/gotty/app/app.go:389 +0xe3
net/http.HandlerFunc.ServeHTTP(0xc20802bd20, 0x7ff015fe4680, 0xc20802e4e0, 0xc208034750)
        /usr/lib/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20800d260, 0x7ff015fe4680, 0xc20802e4e0, 0xc208034750)
        /usr/lib/go/src/net/http/server.go:1541 +0x17d
github.com/yudai/gotty/app.func·001(0x7ff015fe4648, 0xc208042320, 0xc208034750)
        /tmp/gotty/src/github.com/yudai/gotty/app/app.go:381 +0xe2
net/http.HandlerFunc.ServeHTTP(0xc20802bd40, 0x7ff015fe4648, 0xc208042320, 0xc208034750)
        /usr/lib/go/src/net/http/server.go:1265 +0x41
github.com/braintree/manners.(*gracefulHandler).ServeHTTP(0xc20802f120, 0x7ff015fe4648, 0xc208042320, 0xc208034750)
        /tmp/gotty/src/github.com/braintree/manners/server.go:277 +0x81
net/http.serverHandler.ServeHTTP(0xc208040240, 0x7ff015fe4648, 0xc208042320, 0xc208034750)
        /usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2080425a0)
        /usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:1751 +0x35e
```

**Comment by xiaods** [comment]
it's fixed in upstream branch. i have test done.
